'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/navbar/navbar';

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleLogin = ()=>{
    console.log('login clicked');
    
  }
  return (
    <html lang="en">
      <div>
      <Navbar onLogin={handleLogin} />
      <main>{children}</main>
    </div>
    </html>
  );
}
